#
# DO NOT MODIFY!!!!
# This file is automatically generated by Racc 1.5.2
# from Racc grammar file "".
#

require 'racc/parser.rb'


require "strscan"
require "stringio"

module FortIO
end

module FortIO::Namelist

  class Scanner 
  
    def initialize (text)
      @s = StringScanner.new(text)
      @in_namelist = nil
    end

    attr_accessor :in_namelist

    def debug_info
      lines  = @s.string.split(/\n/)
      lineno = @s.string[0...@s.pos].split(/\n/).size
      info = ""
      if lineno > 1
        info << format("   %4i: %s\n", lineno-1, lines[lineno-2])
      end
      info << format(">> %4i: %s\n", lineno, lines[lineno-1])
      if lineno <= lines.size - 1
        info << format("   %4i: %s\n", lineno+1, lines[lineno])
      end
      info
    end

    def yylex
      while @s.rest?
        unless @in_namelist
          case
          when @s.scan(/\A([\$&])/)              ### {$|&}
            @in_namelist = "dummy"
            return [
              @s[0], 
              nil
            ]
          when @s.scan(/\A[^\$&]/)
            next
          end       
        else
          case
          when @s.scan(/\A\(/)
            return [
              '(',
              nil
            ]
          when @s.scan(/\A\)/)
            return [
              ')',
              nil
            ]
          when @s.scan(/\A\:/)
            return [
              ':',
              nil
            ]
          when @s.scan(/\A[+-]?(\d+)\.(\d+)?([ED][+-]?(\d+))?/i) ### float
            return [                              ### 1.2E+3, 1.E+3, 1.2E3
              :FLOAT,                             ### 1.2, 1.
              @s[0].sub(/D/i,'e').sub(/\.e/,".0e").to_f
            ]
          when @s.scan(/\A[+-]?\.(\d+)([ED][+-]?(\d+))?/i)       ### float
            return [                              ### .2E+3, -.2E+3, .2E3
              :FLOAT,                             ### .2, -.2
              @s[0].sub(/D/i,'e').sub(/\./, '0.').to_f
            ]
          when @s.scan(/\A[+-]?(\d+)[ED][+-]?(\d+)/i)            ### float
            return [                              ### 12E+3, 12E3, 0E0
              :FLOAT, 
              @s[0].sub(/D/i,'e').to_f
            ]
          when @s.scan(/\A\d+[a-z_]\w*/i)         ### STRING-Like
            return [
              :STRINGLIKE,
              @s[0]
            ]
          when @s.scan(/\A[\-\+]?\d+/)            ### digits
            return [
              :DIGITS, 
              Integer(@s[0])
            ]
          when @s.scan(/\A'((?:''|[^'])*)'/)      ### 'quoted string'
            return [
              :STRING, 
              @s[1].gsub(/''/, "'")
            ]
          when @s.scan(/\A"((?:""|[^"])*)"/)      ### 'double-quoted string'
            return [
              :STRING, 
              @s[1].gsub(/""/, '"')
            ]
          when @s.scan(/\A,/)                     ### ,
            @s.scan(/\A[ \t]+/)
            while @s.scan(/\A\n[ \t]*/) or @s.scan(/\A\![^\n]*/)
              ### skip comment
            end
            if @s.scan(/\A\&[ \t]*\n[ \t]*\&/)  ### & &
              return [
                ',',
                nil
              ]
            elsif @s.match?(/\A[a-z]\w*\s*,/i) 
              return [
                ',', 
                nil
              ]
            elsif @s.match?(/\A[a-z]\w*/i) or @s.match?(/\A[\&\$\/\!]/)
              return [
                :COMMA, 
                nil
              ]
            elsif @s.match?(/\A,/)
              return [
                :NIL,
                nil
              ]
            else
              return [
                ',',
                nil
              ]
            end
          when @s.scan(/\A\&[ \t]*\n[ \t]*\&/)      ### & &
            next            
          when @s.scan(/\A[\$&\/=\(\):*]/)        ### {$|&|/|,|=|(|)|:|*}
            return [
              @s[0], 
              nil
            ]
          when @s.scan(/\A_\w*/i)                 ### STRING-Like
            return [
              :STRINGLIKE,
              @s[0]
            ]
          when @s.scan(/\A\.t.*?\./i)             ### LOGICAL true
            return [                 
              :LOGICAL,
              true,
            ]
          when @s.scan(/\A\.f.*?\./i)             ### LOGICAL false
            return [
              :LOGICAL,
              false,
            ]
          when @s.match?(/\At[^\w]/i)             ### LOGICAL true
            @s.scan(/\At/i)
            ms = @s[0]
            if @s.match?(/\A[ \t]*=/)
              return [
                :IDENT,
                ms
              ]
            else
              return [                 
                :LOGICAL,
                true,
              ]
            end
          when @s.match?(/\Af[^\w]/i)             ### LOGICAL false
            @s.scan(/\Af/i)
            ms = @s[0]
            if @s.match?(/\A[ \t]*=/)
              return [
                :IDENT,
                ms
              ]
            else
              return [                 
                :LOGICAL,
                false,
              ]
            end
          when @s.scan(/\A[a-z]\w*/i)             ### IDENT or LOGICAL
            return [
              :IDENT,
              @s[0]
            ]
          when @s.scan(/\A\n/)                    ### newline
            return [
              :NL,
              nil
            ]
            next
          when @s.scan(/\A[ \t]+/)                ### blank
            next
          when @s.scan(/\A![^\n]*?\n/)            ### comment
            next
          else
            @s.rest =~ /\A(.*)$/
            raise "namelist parse error ('#{$1}')\n" + debug_info
          end
        end
      end
    end

  end
end

module FortIO
  module Namelist
    class Parser < Racc::Parser

module_eval(<<'...end fortran_namelist.y/module_eval...', 'fortran_namelist.y', 130)

  def parse (str)
    @scan = FortIO::Namelist::Scanner.new(str)
    @root = {}
    begin
      @yydebug = true
      do_parse
    rescue Racc::ParseError => err
      message = ""
      message << "namelist " << err.message[1..-1] 
      if @scan.in_namelist and @scan.in_namelist != "dummy"
        message << " in &#{@scan.in_namelist} ... &end"
      end
      message << "\n"
      message << @scan.debug_info
      raise RuntimeError, message
    end
    return @root
  end

  def next_token
    return @scan.yylex
  end

...end fortran_namelist.y/module_eval...
##### State transition tables begin ###

racc_action_table = [
    46,    32,    63,    45,     4,     5,    37,    14,    39,    61,
    40,    41,    44,    47,    46,    64,    60,    45,    15,    13,
    37,    22,    39,    10,    40,    41,    44,    47,    45,    31,
    22,    54,    53,    39,    45,    40,    41,    44,    13,    39,
    45,    40,    41,    44,    27,    57,    28,    40,    41,    44,
    13,     7,    13,    57,     4,     5,    10,    44,    28,     4,
     5,    21,    24,    18,     4,     5,    21,    57,    18,    49,
    13,    44,    13,    55,    56,    59,    22,    22,    66,    68,
    49,    72,    73,    49 ]

racc_action_check = [
    26,    26,    55,    26,     0,     0,    26,     6,    26,    49,
    26,    26,    26,    26,    67,    55,    49,    67,     7,     3,
    67,    25,    67,     3,    67,    67,    67,    67,    34,    25,
    11,    34,    34,    34,    53,    34,    34,    34,    21,    53,
    56,    53,    53,    53,    21,    56,    21,    56,    56,    56,
    59,     1,    16,    45,     1,     1,    16,    45,    59,     9,
     9,     9,    19,     9,    23,    23,    23,    66,    23,    27,
    28,    66,    31,    35,    39,    48,    50,    51,    58,    60,
    61,    68,    70,    72 ]

racc_action_pointer = [
     1,    51,   nil,    17,   nil,   nil,     2,    18,   nil,    56,
   nil,    28,   nil,   nil,   nil,   nil,    50,   nil,   nil,    57,
   nil,    36,   nil,    61,   nil,    19,    -5,    56,    68,   nil,
   nil,    70,   nil,   nil,    20,    61,   nil,   nil,   nil,    60,
   nil,   nil,   nil,   nil,   nil,    40,   nil,   nil,    66,    -3,
    74,    75,   nil,    26,   nil,    -3,    32,   nil,    66,    48,
    66,    67,   nil,   nil,   nil,   nil,    54,     9,    69,   nil,
    73,   nil,    70,   nil,   nil ]

racc_action_default = [
   -49,   -49,    -2,   -13,    -5,    -6,   -49,   -49,    -1,   -49,
    -8,    -9,   -10,   -11,    -7,    75,   -13,    -4,   -14,   -49,
   -16,   -49,   -12,   -49,   -15,   -49,   -49,   -49,   -21,    -3,
   -17,   -23,   -18,   -19,   -25,   -26,   -27,   -28,   -32,   -38,
   -34,   -35,   -36,   -37,   -39,   -49,   -41,   -42,   -49,   -45,
   -22,   -24,   -29,   -49,   -31,   -49,   -49,   -38,   -49,   -49,
   -49,   -49,   -30,   -43,   -44,   -33,   -49,   -49,   -46,   -47,
   -49,   -20,   -49,   -40,   -48 ]

racc_goto_table = [
    48,    33,    25,    26,    58,    52,    17,    19,    20,    50,
     9,     1,    51,     2,     8,    16,    65,   nil,   nil,   nil,
    29,    19,    30,    23,    62,    70,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,    69,   nil,   nil,   nil,   nil,   nil,
    25,    67,    71,   nil,   nil,    74 ]

racc_goto_check = [
    13,    12,     8,    11,    18,    16,     6,     7,    10,     8,
     4,     1,     8,     2,     2,     5,    17,   nil,   nil,   nil,
     6,     7,    10,     4,    16,    18,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,    13,   nil,   nil,   nil,   nil,   nil,
     8,    11,    12,   nil,   nil,    13 ]

racc_goto_pointer = [
   nil,    11,    13,   nil,     7,     6,    -3,    -2,   -19,   nil,
    -1,   -18,   -25,   -27,   nil,   nil,   -29,   -40,   -41,   nil ]

racc_goto_default = [
   nil,   nil,   nil,     3,   nil,   nil,   nil,     6,    11,    12,
   nil,   nil,   nil,   nil,    34,    35,    36,    38,    42,    43 ]

racc_reduce_table = [
  0, 0, :racc_error,
  2, 21, :_reduce_none,
  1, 21, :_reduce_none,
  5, 22, :_reduce_3,
  3, 22, :_reduce_4,
  1, 27, :_reduce_none,
  1, 27, :_reduce_none,
  2, 23, :_reduce_7,
  1, 24, :_reduce_none,
  1, 24, :_reduce_none,
  1, 24, :_reduce_none,
  1, 28, :_reduce_none,
  2, 28, :_reduce_none,
  0, 29, :_reduce_none,
  1, 26, :_reduce_none,
  2, 26, :_reduce_15,
  1, 25, :_reduce_16,
  3, 25, :_reduce_17,
  3, 30, :_reduce_18,
  3, 30, :_reduce_19,
  6, 30, :_reduce_20,
  1, 31, :_reduce_none,
  2, 31, :_reduce_none,
  2, 31, :_reduce_none,
  3, 31, :_reduce_none,
  1, 32, :_reduce_none,
  1, 32, :_reduce_none,
  1, 34, :_reduce_none,
  1, 34, :_reduce_28,
  2, 34, :_reduce_29,
  3, 34, :_reduce_30,
  2, 34, :_reduce_31,
  1, 36, :_reduce_32,
  3, 36, :_reduce_33,
  1, 37, :_reduce_none,
  1, 37, :_reduce_none,
  1, 37, :_reduce_none,
  1, 37, :_reduce_none,
  1, 38, :_reduce_none,
  1, 38, :_reduce_none,
  5, 39, :_reduce_40,
  1, 35, :_reduce_41,
  1, 35, :_reduce_42,
  3, 35, :_reduce_43,
  3, 35, :_reduce_44,
  1, 33, :_reduce_45,
  3, 33, :_reduce_46,
  3, 33, :_reduce_47,
  5, 33, :_reduce_48 ]

racc_reduce_n = 49

racc_shift_n = 75

racc_token_table = {
  false => 0,
  :error => 1,
  :NL => 2,
  "&" => 3,
  "$" => 4,
  :IDENT => 5,
  :COMMA => 6,
  "/" => 7,
  "(" => 8,
  ")" => 9,
  "=" => 10,
  :NIL => 11,
  "," => 12,
  :DIGITS => 13,
  "*" => 14,
  :STRING => 15,
  :LOGICAL => 16,
  :FLOAT => 17,
  :STRINGLIKE => 18,
  ":" => 19 }

racc_nt_base = 20

racc_use_result_var = true

Racc_arg = [
  racc_action_table,
  racc_action_check,
  racc_action_default,
  racc_action_pointer,
  racc_goto_table,
  racc_goto_check,
  racc_goto_default,
  racc_goto_pointer,
  racc_nt_base,
  racc_reduce_table,
  racc_token_table,
  racc_shift_n,
  racc_reduce_n,
  racc_use_result_var ]

Racc_token_to_s_table = [
  "$end",
  "error",
  "NL",
  "\"&\"",
  "\"$\"",
  "IDENT",
  "COMMA",
  "\"/\"",
  "\"(\"",
  "\")\"",
  "\"=\"",
  "NIL",
  "\",\"",
  "DIGITS",
  "\"*\"",
  "STRING",
  "LOGICAL",
  "FLOAT",
  "STRINGLIKE",
  "\":\"",
  "$start",
  "namelist",
  "group",
  "group_header",
  "separator",
  "varlist",
  "group_end",
  "group_prefix",
  "nls",
  "blank",
  "vardef",
  "equal",
  "rvalues",
  "array_spec",
  "rlist",
  "ident_list",
  "element",
  "constant",
  "real",
  "complex" ]

Racc_debug_parser = false

##### State transition tables end #####

# reduce 0 omitted

# reduce 1 omitted

# reduce 2 omitted

module_eval(<<'.,.,', 'fortran_namelist.y', 28)
  def _reduce_3(val, _values, result)
     @root[val[0]] = val[2]; @scan.in_namelist = nil
    result
  end
.,.,

module_eval(<<'.,.,', 'fortran_namelist.y', 30)
  def _reduce_4(val, _values, result)
     @root[val[0]] = []; @scan.in_namelist = nil
    result
  end
.,.,

# reduce 5 omitted

# reduce 6 omitted

module_eval(<<'.,.,', 'fortran_namelist.y', 38)
  def _reduce_7(val, _values, result)
     result = val[1].downcase; @scan.in_namelist = val[1].downcase
    result
  end
.,.,

# reduce 8 omitted

# reduce 9 omitted

# reduce 10 omitted

# reduce 11 omitted

# reduce 12 omitted

# reduce 13 omitted

# reduce 14 omitted

module_eval(<<'.,.,', 'fortran_namelist.y', 54)
  def _reduce_15(val, _values, result)
     raise Racc::ParseError, "\nparse error (&)" unless val[1] =~ /\Aend\Z/i
    result
  end
.,.,

module_eval(<<'.,.,', 'fortran_namelist.y', 57)
  def _reduce_16(val, _values, result)
     result = [val[0]]
    result
  end
.,.,

module_eval(<<'.,.,', 'fortran_namelist.y', 59)
  def _reduce_17(val, _values, result)
     result = val[0] + [val[2]]
    result
  end
.,.,

module_eval(<<'.,.,', 'fortran_namelist.y', 63)
  def _reduce_18(val, _values, result)
     result = ParamDef.new(val[0].downcase, nil, "")
    result
  end
.,.,

module_eval(<<'.,.,', 'fortran_namelist.y', 65)
  def _reduce_19(val, _values, result)
     result = ParamDef.new(val[0].downcase, nil, val[2])
    result
  end
.,.,

module_eval(<<'.,.,', 'fortran_namelist.y', 67)
  def _reduce_20(val, _values, result)
     result = ParamDef.new(val[0].downcase, val[2], val[5])
    result
  end
.,.,

# reduce 21 omitted

# reduce 22 omitted

# reduce 23 omitted

# reduce 24 omitted

# reduce 25 omitted

# reduce 26 omitted

# reduce 27 omitted

module_eval(<<'.,.,', 'fortran_namelist.y', 81)
  def _reduce_28(val, _values, result)
     result = [nil, nil]
    result
  end
.,.,

module_eval(<<'.,.,', 'fortran_namelist.y', 83)
  def _reduce_29(val, _values, result)
     result = val[0] + val[1]
    result
  end
.,.,

module_eval(<<'.,.,', 'fortran_namelist.y', 85)
  def _reduce_30(val, _values, result)
     result = val[0] + val[2]
    result
  end
.,.,

module_eval(<<'.,.,', 'fortran_namelist.y', 87)
  def _reduce_31(val, _values, result)
     result = val[0] + [nil]
    result
  end
.,.,

module_eval(<<'.,.,', 'fortran_namelist.y', 90)
  def _reduce_32(val, _values, result)
     result = [val[0]]
    result
  end
.,.,

module_eval(<<'.,.,', 'fortran_namelist.y', 92)
  def _reduce_33(val, _values, result)
     result = [val[2]] * val[0]
    result
  end
.,.,

# reduce 34 omitted

# reduce 35 omitted

# reduce 36 omitted

# reduce 37 omitted

# reduce 38 omitted

# reduce 39 omitted

module_eval(<<'.,.,', 'fortran_namelist.y', 106)
  def _reduce_40(val, _values, result)
     result = Complex(val[1],val[3])
    result
  end
.,.,

module_eval(<<'.,.,', 'fortran_namelist.y', 109)
  def _reduce_41(val, _values, result)
     result = [val[0]]
    result
  end
.,.,

module_eval(<<'.,.,', 'fortran_namelist.y', 111)
  def _reduce_42(val, _values, result)
     result = [val[0]]
    result
  end
.,.,

module_eval(<<'.,.,', 'fortran_namelist.y', 113)
  def _reduce_43(val, _values, result)
     result = val[0] + [val[2]]
    result
  end
.,.,

module_eval(<<'.,.,', 'fortran_namelist.y', 115)
  def _reduce_44(val, _values, result)
     result = val[0] + [val[2]]
    result
  end
.,.,

module_eval(<<'.,.,', 'fortran_namelist.y', 118)
  def _reduce_45(val, _values, result)
     result = [val[0]-1]
    result
  end
.,.,

module_eval(<<'.,.,', 'fortran_namelist.y', 120)
  def _reduce_46(val, _values, result)
     result = [(val[0]-1)..(val[2]-1)]
    result
  end
.,.,

module_eval(<<'.,.,', 'fortran_namelist.y', 122)
  def _reduce_47(val, _values, result)
     result = [val[0]-1] + val[2]
    result
  end
.,.,

module_eval(<<'.,.,', 'fortran_namelist.y', 124)
  def _reduce_48(val, _values, result)
     result = [(val[0]-1)..(val[2]-1)] + val[4]
    result
  end
.,.,

def _reduce_none(val, _values, result)
  val[0]
end

    end   # class Parser
  end   # module Namelist
end   # module FortIO


